version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_DIR: "C:\\dotnet"

phases:
  install:
    commands:
      - echo "Installing .NET 8 SDK..."
      - $env:DOTNET_DIR = "C:\dotnet"
      - Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version 8.0.100 -InstallDir $env:DOTNET_DIR
      - $env:PATH = "$env:DOTNET_DIR;$env:PATH"
      - & "$env:DOTNET_DIR\dotnet.exe" --info
      - echo "Restoring packages..."
      - & "$env:DOTNET_DIR\dotnet.exe" restore
  build:
    commands:
      - echo "Building..."
      - & "$env:DOTNET_DIR\dotnet.exe" build -c $env:CONFIGURATION --no-restore
  post_build:
    commands:
      - echo "Publishing web projects..."
      - |
        Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
          if (Select-String -Path $_.FullName -Pattern 'Microsoft.NET.Sdk.Web' -Quiet) {
            Write-Host "Publishing $($_.FullName)"
            & "$env:DOTNET_DIR\dotnet.exe" publish $_.FullName -c $env:CONFIGURATION -o "$env:PUBLISH_DIR\$($_.BaseName)"
          }
        }
artifacts:
  base-directory: output
  files:
    - '**/*'
